[package]
name = "quartz_commands"
version = "0.1.1"
authors = ["Cassy343", "maddymakesgames"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "1.5.4"
qc_macros = { version = "*", path = "./qc_macros" }

[[example]]
name = "sample"